### ISSUE TITLE
request: change the data fetch timing

### ISSUE THREAD

**Issue by z-p1** [y-o0/damdata#3]
the data fetch timing should be changed to 
at least 20 minutes after every hour to reduce data loss.
[data_fetch_timing.txt](https://github.com/y-o0/damdata/files/4977491/data_fetch_timing.txt)

**Comment by y-o0** [comment]
Thanks for the suggestion and providing data.
I agree with the idea that delay will improve the data loss rate, but there are another concern: Github Actions never fires on time.

https://github.com/y-o0/damdata/blob/d30100f7d96463cdf04bbae5f909061d35d2b567/.github/workflows/fire.yml#L5

According to the setting, GA should be fired at 5 minutes every hour.
However, currently that fires at around 15 minutes hourly.

🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬

OK, so then I will fix it, considering the behaviour described above.

**Comment by y-o0** [comment]
10分遅らせて対応しました。目論見では毎時25分あたりに発火されれば...と思っていますが、うまく行かなければまた様子を見て適宜変更していきます。

**Comment by z-p1** [comment]
ご対応ありがとうございます。
crontab設定を見ておかしいなとは思っていたんですが、
定刻で発火してくれないんですね。
